version: '3.8'

services:
  backend:
    build:
      context: ./parser_summerTask
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - my_db
    environment:
      - DATABASE_URL=postgresql://postgres:Aat8912000!@my_db:5432/hh
    command: >
      bash -c "
      python -m parser.main &&
      uvicorn parser.api:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: ./front_summer_task
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  my_db:
    image: postgres:13
    container_name: my_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Aat8912000!
      - POSTGRES_DB=hh
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
